apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: createcerts-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: createcerts-1-0-gamma
    app.kubernetes.io/part-of: fulcio-1-0-gamma
  name: createcerts-1-0-gamma
spec:
  selector:
    app.kubernetes.io/instance: createcerts-1-0-gamma
status:
  loadBalancer: {}
