apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: createcerts-1-0-gamma
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/fulcio-1-0-gamma/createcerts-1-0-gamma@sha256:c7fb5a099f3b68b1c5f5935d8075c98f8913fa9a9dcfd2989d3801d5590018b7
        name: my-go
        resources: {}
status: {}
