apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fulcio-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fulcio-1-0-gamma
    app.kubernetes.io/part-of: fulcio-1-0-gamma
  name: fulcio-1-0-gamma
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: fulcio-1-0-gamma
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fulcio-1-0-gamma
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/fulcio-1-0-gamma/fulcio-1-0-gamma@sha256:dc1f10ddc34cce14a6e35f1448b6d1af1804dfbdb2cfe340ec5d133689a8fa92
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 5555
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
