apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fulcio-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fulcio-1-0-gamma
    app.kubernetes.io/part-of: fulcio-1-0-gamma
  name: fulcio-1-0-gamma
spec:
  ports:
  - port: 5555
    targetPort: 5555
  selector:
    app.kubernetes.io/instance: fulcio-1-0-gamma
status:
  loadBalancer: {}
